"""Mirror of release info

Generated by tools/update_versions.py
"""

# The integrity hashes can be computed with
# shasum -b -a 256 [downloaded file]
PROBE_RS_VERSIONS = {
    "0.24.0": [
        {
            "name": "probe_rs_tools_x86_64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.24.0/probe-rs-tools-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "21e8d7df39fa0cdc9a0421e0ac2ac5ba81ec295ea11306f26846089f6fe975c0",
            "strip_prefix": "probe-rs-tools-x86_64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.24.0/probe-rs-tools-aarch64-unknown-linux-gnu.tar.xz",
            "sha256": "95d91ebe08868d5119a698e3268ff60a4d71d72afa26ab207d43c807c729c90a",
            "strip_prefix": "probe-rs-tools-aarch64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.24.0/probe-rs-tools-x86_64-apple-darwin.tar.xz",
            "sha256": "0e35cc92ff34af1b1c72dd444e6ddd57c039ed31c2987e37578864211e843cf1",
            "strip_prefix": "probe-rs-tools-x86_64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.24.0/probe-rs-tools-aarch64-apple-darwin.tar.xz",
            "sha256": "7140d9c2c61f8712ba15887f74df0cb40a7b16728ec86d5f45cc93fe96a0a29a",
            "strip_prefix": "probe-rs-tools-aarch64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_pc_windows_msvc",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.24.0/probe-rs-tools-x86_64-pc-windows-msvc.zip",
            "sha256": "2a11a8e5be39302eee7746251f6b8355e43440bc687393f6c5b1aa8963ee11b4",
            "exec_compatible_with": [
                "@platforms//os:windows",
                "@platforms//cpu:x86_64",
            ],
        },
    ],
    "0.25.0": [
        {
            "name": "probe_rs_tools_x86_64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.25.0/probe-rs-tools-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "270f7e14e5d348d50d5a4d9a7cdad0ed218812b28f3a9d92cc7e18b8b2febe41",
            "strip_prefix": "probe-rs-tools-x86_64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.25.0/probe-rs-tools-aarch64-unknown-linux-gnu.tar.xz",
            "sha256": "1ad4a634a764bbc2ec18229542c53329e88f983fc43d492f932a26549579c92e",
            "strip_prefix": "probe-rs-tools-aarch64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.25.0/probe-rs-tools-x86_64-apple-darwin.tar.xz",
            "sha256": "0ee4ac219020f302c3885203ec08ebe7b72d65ffb7ddc7d6d41b51df1201a828",
            "strip_prefix": "probe-rs-tools-x86_64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.25.0/probe-rs-tools-aarch64-apple-darwin.tar.xz",
            "sha256": "caad242802014ed87fecd0e92cda81898e723a4e999c4e12a8fa0ebb0931dab3",
            "strip_prefix": "probe-rs-tools-aarch64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_pc_windows_msvc",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.25.0/probe-rs-tools-x86_64-pc-windows-msvc.zip",
            "sha256": "e1c7e22c25514830377fb2c7e836d27de7d6ca5e8c2d3574588ea8fa7e347971",
            "exec_compatible_with": [
                "@platforms//os:windows",
                "@platforms//cpu:x86_64",
            ],
        },
    ],
    "0.26.0": [
        {
            "name": "probe_rs_tools_x86_64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.26.0/probe-rs-tools-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "e55c39bd4271b26dcae9229f4d66fffd0c3d0654dd3ede46d45fe3eabe3079c4",
            "strip_prefix": "probe-rs-tools-x86_64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.26.0/probe-rs-tools-aarch64-unknown-linux-gnu.tar.xz",
            "sha256": "5e833faf83034007e7dd496e025baeb63919a8a7cecd1baebe142460c5631a94",
            "strip_prefix": "probe-rs-tools-aarch64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.26.0/probe-rs-tools-x86_64-apple-darwin.tar.xz",
            "sha256": "6c5a952c59075f579c76318ff32c992596ca11ecc379f592a0a52ed596a0dbf8",
            "strip_prefix": "probe-rs-tools-x86_64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.26.0/probe-rs-tools-aarch64-apple-darwin.tar.xz",
            "sha256": "473417d3b2582017e1eb3efe686ecf7f9d19b940d853b3b978cb8cd1d2f9c052",
            "strip_prefix": "probe-rs-tools-aarch64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_pc_windows_msvc",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.26.0/probe-rs-tools-x86_64-pc-windows-msvc.zip",
            "sha256": "4805595b10441ebdc462b865bd289cb9ac728e64b172675f67d226932a590caa",
            "exec_compatible_with": [
                "@platforms//os:windows",
                "@platforms//cpu:x86_64",
            ],
        },
    ],
    "0.27.0": [
        {
            "name": "probe_rs_tools_x86_64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.27.0/probe-rs-tools-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "314c40db7ded9ae5622c6af8fe5149bcf5c507d7d6f5b7a415d6acf8d2005cb0",
            "strip_prefix": "probe-rs-tools-x86_64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.27.0/probe-rs-tools-aarch64-unknown-linux-gnu.tar.xz",
            "sha256": "7aed7af58c9e267b7145490de61d0147033fadb0a70313fe7dbd363bfd98a728",
            "strip_prefix": "probe-rs-tools-aarch64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.27.0/probe-rs-tools-x86_64-apple-darwin.tar.xz",
            "sha256": "c00a87173008b8279c8d2669e90ce878629abb95ceaa003099adb68d62f3fafb",
            "strip_prefix": "probe-rs-tools-x86_64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.27.0/probe-rs-tools-aarch64-apple-darwin.tar.xz",
            "sha256": "7b1ad0d61f6355a9f095e4d06a5e6149ad9824f4725d4976104486941d652d5c",
            "strip_prefix": "probe-rs-tools-aarch64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_pc_windows_msvc",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.27.0/probe-rs-tools-x86_64-pc-windows-msvc.zip",
            "sha256": "88a80e304caf706235c5fd2c75e8c2f6280ff86472348fc3bef19eadb9e47b8c",
            "exec_compatible_with": [
                "@platforms//os:windows",
                "@platforms//cpu:x86_64",
            ],
        },
    ],
    "0.28.0": [
        {
            "name": "probe_rs_tools_x86_64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.28.0/probe-rs-tools-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "8b5d6327fb52715c8045c1f9261c335b2faa49c4b7f963e197251533f0bdb4f7",
            "strip_prefix": "probe-rs-tools-x86_64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.28.0/probe-rs-tools-aarch64-unknown-linux-gnu.tar.xz",
            "sha256": "c87b220e9a292825c84708b4ac1df408d7dc7bf46cacffd6c70c0d4998366e35",
            "strip_prefix": "probe-rs-tools-aarch64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.28.0/probe-rs-tools-x86_64-apple-darwin.tar.xz",
            "sha256": "44201772971d5f99064058fe8f38afa20801876c28d3838253cf165d14f83c35",
            "strip_prefix": "probe-rs-tools-x86_64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.28.0/probe-rs-tools-aarch64-apple-darwin.tar.xz",
            "sha256": "b072d59b1dcea5e018c3e9824491453c3c76d6a351d607e2a64cebb88e628588",
            "strip_prefix": "probe-rs-tools-aarch64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_pc_windows_msvc",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.28.0/probe-rs-tools-x86_64-pc-windows-msvc.zip",
            "sha256": "b91a04779733f9808541f80bf1a3f4d2d9294e8f31a72883771b86775471af38",
            "exec_compatible_with": [
                "@platforms//os:windows",
                "@platforms//cpu:x86_64",
            ],
        },
    ],
    "0.29.0": [
        {
            "name": "probe_rs_tools_x86_64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.29.0/probe-rs-tools-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "6342f69d446c10b0070f9690e4a48119c1646ddf322e4a51701231532eaaa645",
            "strip_prefix": "probe-rs-tools-x86_64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.29.0/probe-rs-tools-aarch64-unknown-linux-gnu.tar.xz",
            "sha256": "f3ce7f9e0a2bc9c89e77f47f4eafd36489aa02f0512d12059c0e023426c3c505",
            "strip_prefix": "probe-rs-tools-aarch64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.29.0/probe-rs-tools-x86_64-apple-darwin.tar.xz",
            "sha256": "3716a274a1252f5e02522d2c2561795efcc87398202438586a8858fdbe3b62f1",
            "strip_prefix": "probe-rs-tools-x86_64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.29.0/probe-rs-tools-aarch64-apple-darwin.tar.xz",
            "sha256": "f3d45cc76e720a148bafe9bfb547cf04b6bc4140794389daec6f7bad5b4c0108",
            "strip_prefix": "probe-rs-tools-aarch64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_pc_windows_msvc",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.29.0/probe-rs-tools-x86_64-pc-windows-msvc.zip",
            "sha256": "ffadfe8083b649ee91f5c658715ea66f5284589a3e90894cb6747f92729da73d",
            "exec_compatible_with": [
                "@platforms//os:windows",
                "@platforms//cpu:x86_64",
            ],
        },
    ],
    "0.29.1": [
        {
            "name": "probe_rs_tools_x86_64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.29.1/probe-rs-tools-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "f2ccb2ee5058559d663a3a4d1947ca1ce80802546aadd48cf355455126ae9758",
            "strip_prefix": "probe-rs-tools-x86_64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.29.1/probe-rs-tools-aarch64-unknown-linux-gnu.tar.xz",
            "sha256": "d30d60e96d8244bd4670f244ec039d9167ca6564828096b2d04edd5d114ee286",
            "strip_prefix": "probe-rs-tools-aarch64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.29.1/probe-rs-tools-x86_64-apple-darwin.tar.xz",
            "sha256": "b6b8ccfd367ddf0ddcd04a23bc0e440087d49c333472b259fe79340fb63e119e",
            "strip_prefix": "probe-rs-tools-x86_64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.29.1/probe-rs-tools-aarch64-apple-darwin.tar.xz",
            "sha256": "74af375061589671644cdfb7fd406b0346da736001f97f33f74d229d7fe5ef6f",
            "strip_prefix": "probe-rs-tools-aarch64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_pc_windows_msvc",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.29.1/probe-rs-tools-x86_64-pc-windows-msvc.zip",
            "sha256": "a1e220225cd09c9474fdf2db219adff4030074e6bdaf6e4f669ff97661d55413",
            "exec_compatible_with": [
                "@platforms//os:windows",
                "@platforms//cpu:x86_64",
            ],
        },
    ],
    "0.30.0": [
        {
            "name": "probe_rs_tools_x86_64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.30.0/probe-rs-tools-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "f35b6bc7c8312811e86687ccdbde4386ce63df12aeab79238c7c5fc86dd31046",
            "strip_prefix": "probe-rs-tools-x86_64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.30.0/probe-rs-tools-aarch64-unknown-linux-gnu.tar.xz",
            "sha256": "fd4bae725ab0cb75cae526ec0b4eef09e2aac3f3f51847d61aa1eac092f2b92e",
            "strip_prefix": "probe-rs-tools-aarch64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.30.0/probe-rs-tools-x86_64-apple-darwin.tar.xz",
            "sha256": "b9c115d36f07f0f1fd7830ef71a9787bc7b95a3f6c989f62cd456647b303b6b3",
            "strip_prefix": "probe-rs-tools-x86_64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.30.0/probe-rs-tools-aarch64-apple-darwin.tar.xz",
            "sha256": "aaf0706747dd59fac2987a1d22654f0f2a51f9288689e919c476cf25fe7b2bfe",
            "strip_prefix": "probe-rs-tools-aarch64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_pc_windows_msvc",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.30.0/probe-rs-tools-x86_64-pc-windows-msvc.zip",
            "sha256": "506abec2c50a414aa4db369d7ca94d7e9fd92fb464ee9478e697d652e4ead27f",
            "exec_compatible_with": [
                "@platforms//os:windows",
                "@platforms//cpu:x86_64",
            ],
        },
    ],
    "0.31.0": [
        {
            "name": "probe_rs_tools_x86_64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.31.0/probe-rs-tools-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "25e6c6792914994cd0b7a6d2f90f28c17ac22a45af8f4424e9a0f44a60ee85f2",
            "strip_prefix": "probe-rs-tools-x86_64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_unknown_linux_gnu",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.31.0/probe-rs-tools-aarch64-unknown-linux-gnu.tar.xz",
            "sha256": "80e4235c3262bf42e93a024124af37d3ddcf05b16bbc3b5b57eff8623061e385",
            "strip_prefix": "probe-rs-tools-aarch64-unknown-linux-gnu",
            "exec_compatible_with": [
                "@platforms//os:linux",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.31.0/probe-rs-tools-x86_64-apple-darwin.tar.xz",
            "sha256": "2ddda8dc7531b6896b585c738e54a255a21ff3b790f4089333e0da63b7856bc1",
            "strip_prefix": "probe-rs-tools-x86_64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:x86_64",
            ],
        },
        {
            "name": "probe_rs_tools_aarch64_apple_darwin",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.31.0/probe-rs-tools-aarch64-apple-darwin.tar.xz",
            "sha256": "ade07f1172a5cc17f8d465bc3d2651e7d06212ef79d150d5b10c7a867a192151",
            "strip_prefix": "probe-rs-tools-aarch64-apple-darwin",
            "exec_compatible_with": [
                "@platforms//os:macos",
                "@platforms//cpu:arm64",
            ],
        },
        {
            "name": "probe_rs_tools_x86_64_pc_windows_msvc",
            "url": "https://github.com/probe-rs/probe-rs/releases/download/v0.31.0/probe-rs-tools-x86_64-pc-windows-msvc.zip",
            "sha256": "d148ced8d2bd0d18267aaeeb35738a3265c2a4132c4991e4bfaa18a1beb3051d",
            "exec_compatible_with": [
                "@platforms//os:windows",
                "@platforms//cpu:x86_64",
            ],
        },
    ],
}
